### ISSUE TITLE
handle toast onTap

### ISSUE THREAD

**Issue by KazantsevLev** [gaurishankar007/flutter_sliding_toast#1]
There is a problem with handling clicks on toast. I display a toast when receiving an event, and I want to perform some actions when clicking on this toast

I suggest the following solution:
Add VoidCallback onTap in .show() and add onTap: onTap in GestureDetector

**Comment by gaurishankar007** [comment]
Thank you for your feedback. I will look into it and get back to you soon.

**Comment by gaurishankar007** [comment]
The onTap callback is added in the new version.
